version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["./gradlew", "bootRun"]

volumes:
  postgres-data:
  keycloak-data:
