version: '3'

services:

  postgres:
    container_name: postgres_app
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "54320:5432"
    volumes:
      - postgres-app-data:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["./gradlew", "--no-daemon", "bootRun"]

volumes:
  postgres-app-data:
  keycloak-data:
