version: '3'

services:

  postgres:
    container_name: postgres_api_data
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54320:5432"
    volumes:
      - postgres-app-data:/var/lib/postgresql/data

  springboot-api:
    container_name: springboot-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    ports:
      - 8082:8080

volumes:
  postgres-app-data:
