version: '3'

services:

  nginx-server:
    container_name: nginx-server
    image: webdev00/nginx-default-proxy:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"

  springboot-api:
    container_name: springboot-api
    image: webdev00/springboot-api:latest
    restart: always
    ports:
      - "8080:8080"

  adminer-pgadmin:
    container_name: adminer-pgadmin
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: ${AWS_RDS_POSTGRES_URI}
    ports:
      - 8082:8080
