version: '3'

services:

  springboot-api:
    container_name: springboot-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: ${AWS_RDS_POSTGRES_URI}
    ports:
      - 8082:8080
