version: '3'

services:

  nginx-server:
    container_name: nginx-server
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf

  postgres:
    container_name: postgres_api_data
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-app-data:/var/lib/postgresql/data

  springboot-api:
    container_name: springboot-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint:
      [
        "./gradlew",
        "--no-daemon",
        "-Dspring.profiles.active=dev",
        "-Dspring.config.location=./src/main/resources/application-dev.yml",
        "bootRun"
      ]

volumes:
  postgres-app-data:
